version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=AnimalCatalog_db'